### ISSUE TITLE
Scons can't find any library on Fedora

### ISSUE THREAD

**Issue by srakitnican** [CauldronDevelopmentLLC/cbang#16]
Trying to build cbang on Fedora 25 unsuccessfully under mock environment.
```
Checking for C library pthread... no
Exception: Need library pthread:
  File "/builddir/build/BUILD/cbang-1.0.1/SConstruct", line 47:
    conf.CBConfig('compiler')
  File "/usr/lib/scons/SCons/SConf.py", line 658:
    ret = self.test(context, *args, **kw)
  File "/builddir/build/BUILD/cbang-1.0.1/config/__init__.py", line 166:
    ret = env.cb_methods[name](conf, **kwargs)
  File "/builddir/build/BUILD/cbang-1.0.1/config/compiler/__init__.py", line 323:
    conf.CBRequireLib('pthread')
  File "/usr/lib/scons/SCons/SConf.py", line 658:
    ret = self.test(context, *args, **kw)
  File "/builddir/build/BUILD/cbang-1.0.1/config/__init__.py", line 111:
    raise Exception, 'Need library ' + lib
```
pthread is present on /usr/lib64/libpthread.so as well as /usr/include/pthread.h, yet it can't find any of those. If I remove the check can't find any other library as well.

By looking at config.log, all issues seems to end with following:

```
  File "/builddir/build/BUILD/cbang-1.0.1/config/compiler/__init__.py", line 20, in __call__
    dep.csig = csig
AttributeError: 'File' object has no attribute 'csig'
```

It looks to me that environment is not set up properly, but I have no idea how to debug this. Any idea on how to look further into this?

**Comment by jcoffland** [comment]
This is an incompatibility with newer versions of scons but  you are using outdated code.  You need to build from the HEAD of the master branch not from the v1.0.1 release tag.

**Comment by srakitnican** [comment]
Thanks! Any idea when a new version will be released?

**Comment by jcoffland** [comment]
There haven't been any real releases of cbang.  I tagged v1.0.1 for another project which needed a fixed reference code.  GitHub automatically adds the source code of any tags to the releases page.

cbang is only used by a handful of subprojects.  It's not intended for use beyond those projects.  I keep everything up to date so that the latest versions all work together.  I know this is not the best practice but cbang and all the projects that use cbang are developed nearly exclusively by me.
